# Generated by Django 3.2.7 on 2021-09-15 22:11

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('quote_id', models.CharField(max_length=256)),
                ('dialogue', models.CharField(blank=True, max_length=245, null=True)),
                ('movie', models.CharField(blank=True, max_length=245, null=True)),
                ('character', models.CharField(blank=True, max_length=245, null=True)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('character_id', models.CharField(max_length=256)),
                ('height', models.CharField(blank=True, max_length=245, null=True)),
                ('race', models.CharField(blank=True, max_length=245, null=True)),
                ('gender', models.CharField(blank=True, max_length=245, null=True)),
                ('spouse', models.CharField(blank=True, max_length=245, null=True)),
                ('death', models.CharField(blank=True, max_length=245, null=True)),
                ('realm', models.CharField(blank=True, max_length=245, null=True)),
                ('hair', models.CharField(blank=True, max_length=245, null=True)),
                ('name', models.CharField(blank=True, max_length=245, null=True)),
                ('wikiUrl', models.CharField(blank=True, max_length=245, null=True)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
