# Generated by Django 3.2.7 on 2021-09-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='favorite_character',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
